### ISSUE TITLE
Consecutive comment lines with different markers are treated as same block

### ISSUE THREAD

**Issue by oddbjornkvalsund** [codejive/java-properties#18]
The javadoc of `Properties.findPropertyCommentLines(Cursor pos)` states:

```
Returns a list of token indices pointing to all the comment lines in a comment block. A list
of comments is considered a block when they are consecutive lines, without any empty lines in
between, using the same comment symbol (so they are either all `!` comments or all `#` ones).
```

However, when running the below test, this proves not to be true:

```
  @Test
  void testCommentsOfDifferentTypesAreNotSameBlock() throws IOException {
      List<String> expectedComments = new ArrayList<>();
      expectedComments.add("# Bonjour");
      expectedComments.add("# Gruß");

      Properties props = new Properties();
      props.load(new StringReader("! Hi\n! Hello\n # Bonjour\n# Gruß\nfoo=bar\n"));

      List<String> comments = props.getComment("foo");
      assertThat(comments).isEqualTo(expectedComments);
  }
```

![Screenshot_20230318_011712](https://user-images.githubusercontent.com/836833/226072557-460b86ba-ce3b-43a6-b4cd-9daffe684d2e.png)

**Comment by quintesse** [comment]
You're absolutely right that the docs and the code are not in sync.
I think I'll update the docs to reflect the current implementation, unless someone objects and can come up with a good use-case for implementing what the docs say.

**Comment by oddbjornkvalsund** [comment]
A use case could be the case when you want to distinguish between a _documentation comment_ and a _disabling comment_.

```
# If max number of of messages is set, messages are paginated,
# else all messages are shown.
! max_number_of_messages_per_screen=100
# The welcome message is presented to the user.
# on the landing screen
welcome_message=Hi there!
```

This might seem far fetched, but for tools using this library this isn't such a weird idea. For example, see the editor below. It has separate columns for `Comment` and `Disabled` and both need to be associated with the same property.

<img width="962" alt="image" src="https://user-images.githubusercontent.com/836833/226314177-38fc9e34-01d7-478a-b32e-41ad84302dfd.png">

**Comment by quintesse** [comment]
The tool argument is perhaps somewhat specific, but you have a point with the documentation vs disabling comment.
Right now if you do what you showed in your example the entire comment block would become a comment of the final `welcome_message` property.

If a user wanted to prevent that they'd have to insert an empty line between the commented out `max_number_of_messages_per_screen` and the next line. Which is not ideal.

Thing is that if I implement it this way the following could happen:

```
props.setProperty("test", "fubar", "# Comment one", "! Comment two");
var comment = props.getComment("test"); // Returns only "! Comment two"
```

And that feels wrong somehow, that getting the value would not return the value just set.
Of course we could check for that and throw an exception perhaps if somebody would try to do that.
But that still feels as somewhat of a hack.

So I'm still somewhat undecided as to what is the best way forward.

**Comment by quintesse** [comment]
I just realized there's also another issue, if I have this situation:

```
# comment one
! comment two
key=value
```

And I run `setComment("key", Collections.emptyList())` to remove the item's comment I can't simply delete the line because then "comment one" would suddenly become the item's comment. So we'd need to leave an empty line to indicate that that comment doesn't belong to the item. But if we then set a new comment for the item we suddenly have an extra empty line. So setting the same comment again for the same item would not result in the same document but would result in:

```
# comment one

! comment two
key=value
```

Which is unfortunate.

A similar situation arises when you take the original document and then run `setComment("key", "# comment two")`. We'd have to detect that because we now set a new comment that has the same starting character as the previous comment we run the risk of inadvertently  merging the two, so to prevent that we'd also have to insert an empty line.

So I'm slowly edging towards the current implementation where all continuous comment lines are just seen as a single block, regardless of the character they start with. Overall it just result in a cleaner implementation and something that's easier to reason about.

It would mean that if a user want to prevent a commented out line to become part of the next item's comment they'd have to insert an empty line themselves, eg:

```
# If max number of of messages is set, messages are paginated,
# else all messages are shown.
! max_number_of_messages_per_screen=100

# The welcome message is presented to the user
# on the landing screen.
welcome_message=Hi there!
```

**Comment by quintesse** [comment]
After a very long time a decided to update the docs and not the code. There's just no way I've been able to come up with a solution where having multiple comment blocks whenever the comment char changes doesn't result in weird corner-cases. Closing.
